name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get info
        run: |
          sw_vers
          system_profiler SPSoftwareDataType

          sysctl -a
          sysctl -n machdep.cpu.brand_string
          free -mh

          sysctl -a | grep mem